### ISSUE TITLE
Api not working properly

### ISSUE THREAD

**Issue by ozair-dev** [dollars0427/image-resize-api#4]
Whenever I try to make a GET or POST request with all parameters, server sends the same response that
```
{
  "status": "Failed",
  "error_message": "File does not exist"
}
```
I have tried with different images but getting same response each time. Can u fix it please?
example url: https://resize.sardo.work?imageUrl=https://images.unsplash.com/photo-1657214059139-dc58d16118ed?ixlib=rb-4.0.3%26ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8%26auto=format%26fit=crop%26w=1472%26q=80&width=100&height=100

**Comment by falconshark** [comment]
Hello Ozair, 

Thank you for your report. As for I had moved the API to a new server without create the temp files folder, It made the image cannot be resized (As the folder is not found) .

Currently it can working now.

**Comment by ozair-dev** [comment]
oh thanks, this is great.
