### ISSUE TITLE
.bin file 

### ISSUE THREAD

**Issue by julptk** [dollars0427/image-resize-api#5]
hello, I need help, why does the image that is generated when downloaded becomes a .bin file? shouldn't it be an image file? Thank You

https://resize.sardo.work/?width=800&height=800&imageUrl=https://i0.wp.com/comic.cosmicscans.my.id/to-not-die/chapter84/1kuhtVZv3II4eglrPOhEmbbZtj8imCU0xp6xSXm0.jpg

**Comment by falconshark** [comment]
Dear julptk,
Hello, I had tried to using Firefox to access and download your image through this url, it's provided a jpeg file and able to read.
May I know that which browser are you using ? Maybe the problem it's caused by browser.

**Comment by julptk** [comment]
i used mobile
![Screenshot_20230512-163157](https://github.com/dollars0427/image-resize-api/assets/56266781/1fde4b5c-7b15-4c39-b1b6-91de7f158b4f)

**Comment by sekedus** [comment]
[Via browser](https://sekedus.com/browser-android/#Via_Browser)? It's working for me, try update your browser & [System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en)

**Comment by julptk** [comment]
It works now, thank you sir, but, can the file that will be stored is JPG and not PNG? thanks again
