### ISSUE TITLE
`feature request` Resize image one dimension

### ISSUE THREAD

**Issue by sekedus** [dollars0427/image-resize-api#6]
Please add `resize an image according to one dimension`.

[https://github.com/gumlet/php-image-resize#resize](https://github.com/gumlet/php-image-resize#resize)

```php
$image = new ImageResize('image.jpg');
$image->resizeToHeight(500);
$image->save('image2.jpg');

$image = new ImageResize('image.jpg');
$image->resizeToWidth(300);
$image->save('image2.jpg');
```

**Comment by falconshark** [comment]
Merged new function with https://github.com/dollars0427/image-resize-api/pull/7.
Also, I had updated the API on server too. Thank you !
